"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { createContext, useContext, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// const DataContext = createContext();
const Pro = createContext();

export default function RootLayout({ children }) {
  const [isHidden, setIsHidden] = useState(true);
  const [is, isSet] = useState(true);

  // const [isDone, setIsDone] = useState([true, false, false]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Pro.Provider value={{ is, isSet }}>{children}</Pro.Provider>
      </body>
    </html>
  );
}

// export const useData = () => useContext(DataContext);
export const usePro = () => useContext(Pro);
